apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations: {}
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: observability
  source:
    path: prod/apps/observability
    repoURL: https://github.com/wer1hub/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true
