apiVersion: v1
data:
  admin: JGFwcjEkMm91UEJOci8kZHJ6dEROSnZRVkxiYWxTeFVNdC9tLgo=
  player: JGFwcjEkSHh1Uy5EMlgkMzZqVnZSZk90UmxERE5qSFM1OFl6Lwo=
kind: Secret
metadata:
  name: loki-ingress-nginx-auth
  namespace: observability
type: Opaque
