apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph
  namespace: graph
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: graph
  template:
    metadata:
      labels:
        app: graph
    spec:
      containers:
        - command:
            - node
            - ./dist/app-local.js
          env:
            - name: INTROSPECTION
              value: "false"
            - name: PROJECT
              value: wer1-graph
          envFrom:
            - secretRef:
                name: doppler-secrets-graph
                optional: false
          image: 956022059432.dkr.ecr.eu-west-1.amazonaws.com/graph:1.73.18
          imagePullPolicy: IfNotPresent
          name: graph
          ports:
            - containerPort: 4001
              name: http
              protocol: TCP
      serviceAccountName: graph
