apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: landing
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: landing-page
      server: https://kubernetes.default.svc
    - namespace: doppler-operator-system
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - "*"
