name: 'Terraform Apply'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    uses: lsdopen/.github/.github/workflows/terraform-root-apply.yaml@main
    with:
      aws-assume-role-arn: ${{ vars.AWS_ASSUME_ROLE_ARN }}
      aws-assume-role-region: ${{ vars.AWS_ASSUME_ROLE_REGION }}
      tailscale: true
    secrets:
      terraform-registry-token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      tailscale-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
      tailscale-secret: ${{ secrets.TAILSCALE_SECRET }}
      tailscale-tags: ${{ secrets.TAILSCALE_TAGS }}
      terraform-env-vars: TF_VAR_sauron_client_id='${{ secrets.SAURON_CLIENT_ID }}' TF_VAR_sauron_client_secret='${{ secrets.SAURON_CLIENT_SECRET }}' TF_VAR_grafana_password='${{ secrets.GRAFANA_PASSWORD }}' TF_VAR_alertmanager_discord_webhooks='${{ secrets.ALERTMANAGER_DISCORD_WEBHOOKS }}'
