apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-private-admin
  namespace: graph
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: graph-private-admin
  template:
    metadata:
      labels:
        app: graph-private-admin
    spec:
      containers:
        - command:
            - node
            - ./dist/admin/app.js
          env:
            - name: INTROSPECTION
              value: 'true'
            - name: PROJECT
              value: wer1-graph-dev
          envFrom:
            - secretRef:
                name: doppler-secrets-graph
                optional: false
          image: 976284867583.dkr.ecr.eu-west-1.amazonaws.com/graph:1.75.0-dev
          imagePullPolicy: IfNotPresent
          name: graph-admin
          ports:
            - containerPort: 4002
              name: http
              protocol: TCP
      serviceAccountName: graph
