apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doppler
  namespace: argocd
  annotations: {}
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: doppler-kubernetes-operator
      repoURL: https://helm.doppler.com/
      targetRevision: 1.5.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true
